# Generated by Django 6.0.2 on 2026-02-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Projeto')),
                ('client_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Cliente')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='Data de Registro')),
                ('status', models.CharField(choices=[('PROSPECT', 'Prospecção'), ('PLANNING', 'Planejamento'), ('DEVELOPMENT', 'Em Desenvolvimento'), ('MAINTENANCE', 'Manutenção'), ('FINISHED', 'Finalizado'), ('PAUSED', 'Pausado')], default='PLANNING', max_length=20)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-start_date'],
            },
        ),
    ]
